### ISSUE TITLE
What has been updated

### ISSUE THREAD

**Issue by Vicky0878** [Tasssiooo/Troygrade-for-desktop#3]
Hey, what's with the 0.3 files you posted, should I download that
He couldn't fix the snowflake file in 0.2：https://share.feijipan.com/s/0aB5WarW

**Comment by Vicky0878** [comment]
What are these things I don't know download that

**Comment by Tasssiooo** [comment]
You can download it if you want, I just made some improvements to the front end.
Yeah, some files don't get fixed, because when they are converted to .troy, they come with some typo that make it doesn't work. (The converter code isn't made by me)
I don't really know what you meant by “these things” but if you meant the files in the release assets, they are executables for each OS. (.deb is for Linux, .exe is for Windows, .dmg is for MAC)

**Comment by Vicky0878** [comment]
ok,There are many files released in 0.3, which I need to download when I run on windows.
Files, and there are many file formats that I don't know and I can't open. It would be better if he could support the saving of troy game files. I also have an idea whether he could reverse convert bin into troy, which would be more perfect.

**Comment by Tasssiooo** [comment]
If you are on Windows, you have to download this one: https://github.com/Tasssiooo/Troygrade-for-desktop/releases/download/v0.0.3-beta/Troygrade.Desktop_0.0.3_x64-setup.exe

**Comment by Vicky0878** [comment]
ok，Thank you. The program size was reduced. Did it compress the code
